server:
  port: 9080
# 公司
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:#localhost:1521:orcl
#    username: scott
#    password: tiger

# 家里
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: daisy
    url: jdbc:mysql://localhost:3306/redis_bilibili?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  redis:
    database: 0 # redis数据库索引id
    host: localhost # 服务器地址 ipv4地址
    port: 6379 # 服务器端口库
    password:  # 服务器连接密码
    timeout: 0 # 连接超时时间 单位：毫秒
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，使用负值表示没有限制
        max-wait: -1 # 连接池最大阻塞等待时间，使用负值表示没有限制
        max-idle: 8 # 连接池最大空闲连接数量
        min-idle: 0 # 连接池最小空闲连接数量
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义的布隆过滤器的参数设定
bloom:
  filter:
    expectedInsertions: 1000 # 预计插入量
    fpp: 0.001F # 容错率